// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MachineInfo struct {
	Cpu                  uint32   `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	CpuUsage             float32  `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	Memory               uint64   `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	MemoryUsage          float32  `protobuf:"fixed32,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MachineInfo) Reset()         { *m = MachineInfo{} }
func (m *MachineInfo) String() string { return proto.CompactTextString(m) }
func (*MachineInfo) ProtoMessage()    {}
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *MachineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MachineInfo.Unmarshal(m, b)
}
func (m *MachineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MachineInfo.Marshal(b, m, deterministic)
}
func (m *MachineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MachineInfo.Merge(m, src)
}
func (m *MachineInfo) XXX_Size() int {
	return xxx_messageInfo_MachineInfo.Size(m)
}
func (m *MachineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MachineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MachineInfo proto.InternalMessageInfo

func (m *MachineInfo) GetCpu() uint32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *MachineInfo) GetCpuUsage() float32 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *MachineInfo) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *MachineInfo) GetMemoryUsage() float32 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

type Reply struct {
	Recv                 bool     `protobuf:"varint,1,opt,name=recv,proto3" json:"recv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetRecv() bool {
	if m != nil {
		return m.Recv
	}
	return false
}

func init() {
	proto.RegisterType((*MachineInfo)(nil), "rpc.MachineInfo")
	proto.RegisterType((*Reply)(nil), "rpc.Reply")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x86, 0xdd, 0x24, 0xc6, 0x64, 0xa2, 0x10, 0xa6, 0x90, 0x60, 0x9a, 0x98, 0x2a, 0x20, 0xa4,
	0x50, 0xf0, 0x07, 0xd8, 0xa8, 0x85, 0xcd, 0x82, 0xb5, 0xac, 0xcb, 0x18, 0x0f, 0x2e, 0xd9, 0x65,
	0x6e, 0xf7, 0x8e, 0xfc, 0xfb, 0x23, 0x9b, 0x14, 0xd7, 0x3d, 0xef, 0x0b, 0xcf, 0x7c, 0x40, 0xa1,
	0x06, 0x9a, 0x5c, 0x6f, 0xd9, 0x38, 0x83, 0x31, 0x5b, 0xdd, 0x9e, 0xa0, 0xf8, 0x52, 0xfa, 0x7f,
	0x37, 0xd1, 0xe7, 0xf4, 0x67, 0xb0, 0x84, 0x58, 0x5b, 0x5f, 0x89, 0x46, 0x74, 0x77, 0x72, 0x41,
	0xac, 0x21, 0xd7, 0xd6, 0xff, 0xf8, 0x83, 0x1a, 0xa8, 0x8a, 0x1a, 0xd1, 0x45, 0x32, 0xd3, 0xd6,
	0x7f, 0x2f, 0x19, 0xef, 0x21, 0x1d, 0x69, 0x34, 0x3c, 0x57, 0x71, 0x23, 0xba, 0x44, 0x6e, 0x09,
	0x1f, 0xe1, 0x76, 0xa5, 0xcd, 0x4b, 0x82, 0x57, 0xac, 0x5d, 0x50, 0xdb, 0x1a, 0xae, 0x25, 0xd9,
	0xfd, 0x8c, 0x08, 0x09, 0x93, 0x3e, 0x86, 0x9d, 0x99, 0x0c, 0xfc, 0xfc, 0x0a, 0x37, 0xef, 0x4c,
	0xe4, 0x88, 0xf1, 0x09, 0xf2, 0x0f, 0x52, 0xec, 0xde, 0x48, 0x39, 0x2c, 0x7b, 0xb6, 0xba, 0xbf,
	0x38, 0xf8, 0x01, 0x42, 0x13, 0x26, 0xb5, 0x57, 0xbf, 0x69, 0xf8, 0xec, 0xe5, 0x1c, 0x00, 0x00,
	0xff, 0xff, 0x26, 0x26, 0xb5, 0xe9, 0xe8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	HeartBeat(ctx context.Context, in *MachineInfo, opts ...grpc.CallOption) (*Reply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) HeartBeat(ctx context.Context, in *MachineInfo, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/rpc.Greeter/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	HeartBeat(context.Context, *MachineInfo) (*Reply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) HeartBeat(ctx context.Context, req *MachineInfo) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Greeter/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).HeartBeat(ctx, req.(*MachineInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _Greeter_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
